spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
auth0.client-id=
auth0.client-secret=
auth0.domain=
auth0.client.realm=
spring.security.oauth2.resourceserver.jwt.audiences=
spring.security.oauth2.resourceserver.jwt.issuer-uri=
logging.level.org.springframework.security=TRACE