spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
auth0.client-id=UsQp3IL9jM2lpUPUSqPKvFMcixqbcEyM
auth0.client-secret=swSK0AcXnrUY7R-01REKzo1RTNOtSLhQ9eoqGTi8_rG9PvGiDXayHqRCOGs3wK-J
auth0.domain=https://dev-xs1u0543frkqrhgs.us.auth0.com/
auth0.client.realm=TOPChoirDirectory
spring.security.oauth2.resourceserver.jwt.audiences=UsQp3IL9jM2lpUPUSqPKvFMcixqbcEyM
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-xs1u0543frkqrhgs.us.auth0.com/
logging.level.org.springframework.security=TRACE